version: '3.9'
services:
  database:
    image: postgres:latest
    container_name: AIChat_232506_bd
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: AIChat_232506
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - AIChat_232506_network

networks:
  AIChat_232506_network:
    driver: bridge

volumes:
  postgres_data:
