version: '3.9'
services:
  database:
    image: postgres:latest
    container_name: AIChat_232506_bd
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: AIChat_232506
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - AIChat_232506_network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"      # API порт
      - "9001:9001"      # Консоль управления
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  AIChat_232506_network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:

